In [1]:
import numpy as np

<h6>Creating array 1D,2D,3D</h6>

In [2]:
ar =np.array([1,2,3])

In [3]:
ar.real

array([1, 2, 3])

In [4]:
arr=np.array([[1,2,3],[4,5,6]])

In [5]:
arr.real

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arrr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
arrr.real

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr[0,2]

3

In [9]:
arr[0,2]=8
arr

array([[1, 2, 8],
       [4, 5, 6]])

<h6>Using Numpy Attributes </h6>

In [10]:
arr.dtype

dtype('int32')

In [11]:
arr.shape

(2, 3)

In [12]:
arr.size

6

In [13]:
arr.T

array([[1, 4],
       [2, 5],
       [8, 6]])

In [14]:
arr.nbytes

24

In [15]:
arr.imag

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
arr.flat

In [17]:
for item in arr.flat:
    print(item)

1
2
8
4
5
6


## Numpy object creation  (zeros,ones,arange,eye,....etc)

In [18]:
zero =np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
one =np.ones((2,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
arg=np.arange(0,22)
arg

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [21]:
lspace= np.linspace(1,5,10)
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [22]:
ey=np.eye(4,4)
ey

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
em=np.empty((4,4))
em

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<h6>Creating Numpy Axis and methods</h6>

In [24]:
ax=np.array([[1,2,3],[4,5,6],[7,8,9]])
ax

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
ax.shape

(3, 3)

In [26]:
ax.sum(axis=0)

array([12, 15, 18])

In [27]:
ax.sum(axis=1)

array([ 6, 15, 24])

In [28]:
ax.argmin()

0

In [29]:
ax.argmax()

8

In [30]:
ax.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

<h6>Numpy Method</h6>

In [33]:
ag=np.arange(99)
ag

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
ag.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
ag.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

<h6>Matrix Operations</h6>

In [39]:
ag.sum()

4851

In [41]:
ag.min()

0

In [42]:
ag.max()

98

In [53]:
aq=np.array([[1,2,3],[4,5,6]])
aq

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
aw=np.array([[7,8,9],[1,2,3]])
aw

array([[7, 8, 9],
       [1, 2, 3]])

In [46]:
aq+aw

array([[ 8, 10, 12],
       [ 5,  7,  9]])

In [48]:
aq-aw

array([[-6, -6, -6],
       [ 3,  3,  3]])

In [51]:
aq*aw

array([[ 7, 16, 27],
       [ 4, 10, 18]])

<h6>finding the number less then 5 in aq array</h6>

In [52]:
np.where(aq>5)

(array([1], dtype=int64), array([2], dtype=int64))